//! ZEB-352 Voice V4: 1:1 DM-call signaling sign/seal/open seam.
//!
//! A signaling packet is canonical-CBOR `VoiceSignal`, device-#2-signed
//! (`dm_signing::sign_dm_packet`) then sealed to the callee via
//! `dm_signing::seal_to_owner` (hybrid public-key encryption). The callee
//! opens with `open_from_owner` + verifies the signature. The call state
//! machine lives in the frontend; this module is the crypto seam + types only.

use crate::dm_outbox::DmReceiveError;
use crate::dm_signing::{self, DmSignError};
use crate::owner_state_types::{DeviceIdentityHash, OwnerAddr};
use ed25519_dalek::SigningKey;
use serde::{Deserialize, Serialize};

/// Discriminant for a DM voice-call signaling packet.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum VoiceSignalKind {
    Invite,
    Accept,
    Decline,
    Cancel,
    End,
}

/// Optional reason attached to a `Decline` signal.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum DeclineReason {
    User,
    Busy,
    Timeout,
}

/// The plaintext body of a voice signaling packet.
///
/// Wire-format: canonical CBOR with short field keys to minimise MTU cost.
/// This struct is signed by the caller's device signing key before sealing.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct VoiceSignal {
    /// Signal kind.
    #[serde(rename = "k")]
    pub kind: VoiceSignalKind,
    /// 16-byte random call-ID generated by the caller for each call
    /// attempt. Used by the frontend to correlate Accept/Decline/End
    /// against the originating Invite.
    #[serde(
        rename = "ci",
        serialize_with = "crate::owner_state_types::serialize_bytes_as_bstr",
        deserialize_with = "crate::owner_state_types::deserialize_bytes_from_bstr"
    )]
    pub call_id: [u8; 16],
    /// OwnerAddr of the calling party.
    #[serde(rename = "cl")]
    pub caller: OwnerAddr,
    /// Optional decline reason; only present on `Decline` signals.
    #[serde(rename = "dr", default, skip_serializing_if = "Option::is_none")]
    pub decline_reason: Option<DeclineReason>,
}

/// A `VoiceSignal` with its Ed25519 device-#2 signature over the CBOR body.
///
/// This is the inner plaintext that is sealed to the callee.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct SignedVoiceSignal {
    /// The signed body.
    #[serde(rename = "bd")]
    pub body: VoiceSignal,
    /// 64-byte Ed25519 signature over the canonical CBOR encoding of `body`.
    #[serde(
        rename = "sg",
        serialize_with = "crate::owner_state_types::serialize_bytes_as_bstr",
        deserialize_with = "crate::owner_state_types::deserialize_bytes_from_bstr"
    )]
    pub sig: [u8; 64],
}

/// IPC → event-loop: a resolved outbound signal ready to publish on
/// `harmony/voice-signal/{callee_owner_hex}`.
#[derive(Debug)]
pub struct VoiceSignalRequest {
    /// Hex-encoded OwnerAddr of the callee (topic routing key).
    pub callee_owner_hex: String,
    /// The sealed ciphertext ready to publish.
    pub sealed: Vec<u8>,
}

/// Sign and seal a `VoiceSignal` for delivery to `callee_x25519_pub`.
///
/// Steps:
///   1. Canonical-CBOR encode the signal body.
///   2. Sign the body bytes with `signing_key` (caller's device Ed25519 key).
///   3. Encode `SignedVoiceSignal { body, sig }` as canonical CBOR.
///   4. Hybrid-seal the signed bytes to `callee_x25519_pub`.
///
/// Returns the sealed ciphertext or a `DmSignError` if sealing fails
/// (e.g., low-order callee key).
pub fn build_sealed_signal(
    signal: &VoiceSignal,
    signing_key: &SigningKey,
    callee_x25519_pub: &[u8; 32],
) -> Result<Vec<u8>, DmSignError> {
    let body_bytes = canonical_cbor(signal);
    let sig = dm_signing::sign_dm_packet(&body_bytes, signing_key);
    let signed = SignedVoiceSignal {
        body: signal.clone(),
        sig,
    };
    let signed_bytes = canonical_cbor(&signed);
    dm_signing::seal_to_owner(callee_x25519_pub, &signed_bytes)
}

/// Open and verify a sealed voice signal.
///
/// Steps:
///   1. Hybrid-open the sealed bytes using `self_x25519_priv`.
///   2. CBOR-decode the `SignedVoiceSignal`.
///   3. Re-encode the body as canonical CBOR and verify the Ed25519 signature
///      against `caller_identity_pub` + `caller_signing_device_hash`.
///
/// Returns the verified `VoiceSignal` on success.
///
/// Error mapping:
///   - `open_from_owner` failure      → `DmReceiveError::DecryptFailed`
///   - CBOR decode failure            → `DmReceiveError::Decode(...)`
///   - Signature / hash mismatch      → propagated from `verify_dm_packet_signature`
pub fn open_sealed_signal(
    self_x25519_priv: &[u8; 32],
    sealed: &[u8],
    caller_identity_pub: &[u8; 64],
    caller_signing_device_hash: DeviceIdentityHash,
) -> Result<VoiceSignal, DmReceiveError> {
    let signed = open_and_decode_unverified(self_x25519_priv, sealed)?;
    verify_decoded_signal(&signed, caller_identity_pub, caller_signing_device_hash)
}

/// Hybrid-open + CBOR-decode a sealed signal **without** verifying the
/// signature. The returned `SignedVoiceSignal` is UNTRUSTED until passed
/// through `verify_decoded_signal` (the `_unverified` suffix is a deliberate
/// trust-boundary marker). Splitting open from verify lets the inbound path
/// open the sealed box once and then verify against each candidate device key
/// (the sealed box is sealed to the recipient's X25519 key — identical for
/// every candidate — so re-opening per device is wasted work).
pub fn open_and_decode_unverified(
    self_x25519_priv: &[u8; 32],
    sealed: &[u8],
) -> Result<SignedVoiceSignal, DmReceiveError> {
    let signed_bytes = dm_signing::open_from_owner(self_x25519_priv, sealed)
        .map_err(|_| DmReceiveError::DecryptFailed)?;
    decode_cbor(&signed_bytes)
        .map_err(|e| DmReceiveError::Decode(format!("voice_signal cbor: {e}")))
}

/// Verify an already-decoded signal's Ed25519 signature against
/// `caller_identity_pub` + `caller_signing_device_hash`. Returns the verified
/// body on success. Re-canonicalizes the body so the verified bytes match
/// exactly what was signed.
pub fn verify_decoded_signal(
    signed: &SignedVoiceSignal,
    caller_identity_pub: &[u8; 64],
    caller_signing_device_hash: DeviceIdentityHash,
) -> Result<VoiceSignal, DmReceiveError> {
    let body_bytes = canonical_cbor(&signed.body);
    dm_signing::verify_dm_packet_signature(
        &body_bytes,
        &signed.sig,
        caller_identity_pub,
        caller_signing_device_hash,
    )?;
    Ok(signed.body.clone())
}

// ── CBOR helpers ─────────────────────────────────────────────────────────────

fn canonical_cbor<T: Serialize>(v: &T) -> Vec<u8> {
    let mut buf = Vec::new();
    ciborium::into_writer(v, &mut buf).expect("CBOR serialize infallible for well-typed values");
    buf
}

fn decode_cbor<T: for<'de> Deserialize<'de>>(
    b: &[u8],
) -> Result<T, ciborium::de::Error<std::io::Error>> {
    ciborium::from_reader(b)
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::dm_signing::{ed25519_priv_to_x25519, ed25519_pub_to_x25519};
    use hkdf::Hkdf;
    use sha2::Sha256;

    // ── Fixture helpers ───────────────────────────────────────────────────────

    /// Build a test caller identity: (SigningKey, identity_pub[64], DeviceIdentityHash,
    /// x25519_priv[32], x25519_pub[32]).
    ///
    /// Mirrors `dm_signing::tests::make_test_identity` for the signing half,
    /// then derives X25519 keys via `ed25519_priv_to_x25519` /
    /// `ed25519_pub_to_x25519`.
    ///
    /// The HKDF expansion mirrors `PrivateIdentity::from_seed`'s Ed25519
    /// sub-key derivation (harmony-identity identity.rs, info =
    /// `"harmony-identity-ed25519-v1"`), making `signing_key` bit-identical
    /// to the key `PrivateIdentity::sign` uses internally.
    fn make_caller_identity(seed_byte: u8) -> (SigningKey, [u8; 64], DeviceIdentityHash) {
        let seed = [seed_byte; 32];
        let private = harmony_identity::PrivateIdentity::from_seed(&seed);
        let public = private.public_identity();
        let identity_pub = public.to_public_bytes();
        let device_hash = DeviceIdentityHash(public.address_hash);

        // Derive the same SigningKey from seed via HKDF — this is bit-identical
        // to what PrivateIdentity::sign uses (proven by dm_signing's
        // `sign_dm_packet_matches_private_identity_sign` test).
        let hk = Hkdf::<Sha256>::new(None, &seed);
        let mut ed_arr = [0u8; 32];
        hk.expand(b"harmony-identity-ed25519-v1", &mut ed_arr)
            .expect("HKDF 32 bytes always succeeds");
        let signing_key = SigningKey::from_bytes(&ed_arr);

        (signing_key, identity_pub, device_hash)
    }

    /// Build a test callee X25519 keypair from an Ed25519 seed byte.
    /// Returns (x25519_priv[32], x25519_pub[32]).
    ///
    /// Derives via `ed25519_priv_to_x25519` / `ed25519_pub_to_x25519` using
    /// a SigningKey constructed from the same HKDF expansion as the caller —
    /// consistent with how real device keys are derived in harmony-identity.
    fn make_callee_x25519(seed_byte: u8) -> ([u8; 32], [u8; 32]) {
        let seed = [seed_byte; 32];
        let hk = Hkdf::<Sha256>::new(None, &seed);
        let mut ed_arr = [0u8; 32];
        hk.expand(b"harmony-identity-ed25519-v1", &mut ed_arr)
            .expect("HKDF 32 bytes");
        let signing_key = SigningKey::from_bytes(&ed_arr);
        let x_priv = *ed25519_priv_to_x25519(&signing_key);
        let x_pub = ed25519_pub_to_x25519(&signing_key.verifying_key().to_bytes())
            .expect("valid Ed25519 → X25519 conversion");
        (x_priv, x_pub)
    }

    /// Construct a canonical test `VoiceSignal`.
    fn test_signal(kind: VoiceSignalKind) -> VoiceSignal {
        VoiceSignal {
            kind,
            call_id: [0xca; 16],
            caller: OwnerAddr([0x11; 16]),
            decline_reason: None,
        }
    }

    // ── Tests ─────────────────────────────────────────────────────────────────

    /// Full round-trip: build_sealed_signal → open_sealed_signal returns the
    /// original VoiceSignal unchanged.
    #[test]
    fn sign_seal_open_round_trip() {
        let (signing_key, identity_pub, device_hash) = make_caller_identity(0x42);
        let (callee_priv, callee_pub) = make_callee_x25519(0x77);

        let signal = test_signal(VoiceSignalKind::Invite);
        let sealed = build_sealed_signal(&signal, &signing_key, &callee_pub)
            .expect("build_sealed_signal must succeed for valid keys");

        let recovered = open_sealed_signal(&callee_priv, &sealed, &identity_pub, device_hash)
            .expect(
                "open_sealed_signal must succeed for correct callee priv + correct caller identity",
            );

        assert_eq!(recovered.kind, VoiceSignalKind::Invite);
        assert_eq!(recovered.call_id, signal.call_id);
        assert_eq!(recovered.caller, signal.caller);
        assert_eq!(recovered.decline_reason, None);
    }

    /// Opening with a different X25519 private key must fail.
    #[test]
    fn wrong_recipient_cannot_open() {
        let (signing_key, _identity_pub, _device_hash) = make_caller_identity(0x42);
        let (_callee_priv, callee_pub) = make_callee_x25519(0x77);
        // Different callee — different private key.
        let (wrong_priv, _wrong_pub) = make_callee_x25519(0x88);

        let signal = test_signal(VoiceSignalKind::Accept);
        let sealed =
            build_sealed_signal(&signal, &signing_key, &callee_pub).expect("seal must succeed");

        // open with wrong recipient priv: AEAD tag mismatch → DecryptFailed
        let (_, identity_pub, device_hash) = make_caller_identity(0x42);
        let err = open_sealed_signal(&wrong_priv, &sealed, &identity_pub, device_hash)
            .expect_err("opening with wrong recipient key must fail");
        assert!(
            matches!(err, DmReceiveError::DecryptFailed),
            "expected DecryptFailed for wrong recipient key, got {err:?}"
        );
    }

    /// Flipping a byte in the sealed ciphertext must cause open to fail.
    #[test]
    fn tampered_sealed_fails() {
        let (signing_key, identity_pub, device_hash) = make_caller_identity(0x42);
        let (callee_priv, callee_pub) = make_callee_x25519(0x77);

        let signal = test_signal(VoiceSignalKind::Cancel);
        let mut sealed =
            build_sealed_signal(&signal, &signing_key, &callee_pub).expect("seal must succeed");

        // Tamper with a byte in the ciphertext region (after the 44-byte header).
        let tamper_idx = sealed.len() / 2;
        sealed[tamper_idx] ^= 0xff;

        let err = open_sealed_signal(&callee_priv, &sealed, &identity_pub, device_hash)
            .expect_err("tampered sealed bytes must fail to open");
        assert!(
            matches!(err, DmReceiveError::DecryptFailed),
            "expected DecryptFailed for tampered ciphertext, got {err:?}"
        );
    }

    /// Opening with correct callee priv but a different caller identity_pub/
    /// device_hash must fail at signature verification.
    #[test]
    fn wrong_caller_identity_fails_verify() {
        let (signing_key, _identity_pub, _device_hash) = make_caller_identity(0x42);
        let (callee_priv, callee_pub) = make_callee_x25519(0x77);
        // Different caller identity — different identity_pub and device_hash.
        let (_sk2, wrong_identity_pub, wrong_device_hash) = make_caller_identity(0x99);

        let signal = test_signal(VoiceSignalKind::End);
        let sealed =
            build_sealed_signal(&signal, &signing_key, &callee_pub).expect("seal must succeed");

        // The sealed box opens fine (correct callee priv), but sig verify fails
        // because we present the wrong caller's identity/device-hash.
        let err = open_sealed_signal(
            &callee_priv,
            &sealed,
            &wrong_identity_pub,
            wrong_device_hash,
        )
        .expect_err("wrong caller identity must fail signature verification");
        assert!(
            matches!(
                err,
                DmReceiveError::SignatureVerificationFailed
                    | DmReceiveError::SigningKeyDoesNotMatchDeviceHash
            ),
            "expected SignatureVerificationFailed or SigningKeyDoesNotMatchDeviceHash for wrong caller identity, got {err:?}"
        );
    }

    /// `open_and_decode_unverified` decodes the (unverified) caller from a
    /// valid sealed signal without checking the signature.
    #[test]
    fn open_and_decode_unverified_returns_caller() {
        let (signing_key, _identity_pub, _device_hash) = make_caller_identity(0x42);
        let (callee_priv, callee_pub) = make_callee_x25519(0x77);

        let signal = test_signal(VoiceSignalKind::Invite);
        let sealed =
            build_sealed_signal(&signal, &signing_key, &callee_pub).expect("seal must succeed");

        let decoded = open_and_decode_unverified(&callee_priv, &sealed)
            .expect("open_and_decode_unverified must succeed for a valid sealed signal");
        assert_eq!(decoded.body.caller, signal.caller);
    }

    /// `open_and_decode_unverified` on a sealed blob addressed to a different
    /// recipient (wrong priv) must fail to open.
    #[test]
    fn open_and_decode_unverified_wrong_priv_fails() {
        let (signing_key, _identity_pub, _device_hash) = make_caller_identity(0x42);
        let (_callee_priv, callee_pub) = make_callee_x25519(0x77);
        let (wrong_priv, _wrong_pub) = make_callee_x25519(0x88);

        let signal = test_signal(VoiceSignalKind::Invite);
        let sealed =
            build_sealed_signal(&signal, &signing_key, &callee_pub).expect("seal must succeed");

        assert!(
            open_and_decode_unverified(&wrong_priv, &sealed).is_err(),
            "open_and_decode_unverified with wrong priv must fail to open"
        );
    }

    /// Decline signals round-trip with the DeclineReason field intact.
    #[test]
    fn decline_with_reason_round_trips() {
        let (signing_key, identity_pub, device_hash) = make_caller_identity(0x42);
        let (callee_priv, callee_pub) = make_callee_x25519(0x77);

        let signal = VoiceSignal {
            kind: VoiceSignalKind::Decline,
            call_id: [0xde; 16],
            caller: OwnerAddr([0x22; 16]),
            decline_reason: Some(DeclineReason::Busy),
        };
        let sealed =
            build_sealed_signal(&signal, &signing_key, &callee_pub).expect("seal must succeed");
        let recovered = open_sealed_signal(&callee_priv, &sealed, &identity_pub, device_hash)
            .expect("open must succeed");

        assert_eq!(recovered.kind, VoiceSignalKind::Decline);
        assert_eq!(recovered.decline_reason, Some(DeclineReason::Busy));
    }
}
